MvcStok/Controllers/MusteriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcStok.Models.Entity;
namespace MvcStok.Controllers
{
    public class MusteriController : Controller
    {
        // GET: Musteri
        MvcDbStokEntities db = new MvcDbStokEntities();
        public ActionResult Index( string p)
        {
            var degerler = from d in db.TBLMUSTERILER select d;
            if (!string.IsNullOrEmpty(p))
            {
                degerler = degerler.Where(m => m.MUSTERIAD.Contains(p));
            }
            return View(degerler.ToList());
          //  var degerler = db.TBLMUSTERILER.ToList();
            //return View(degerler);
        }
        [HttpGet]
        public ActionResult YeniMusteri()
        {
            return View();
        }
        [HttpPost]
        public ActionResult YeniMusteri(TBLMUSTERILER p1)
        {
            if (!ModelState.IsValid)
            {
                return View("YeniMusteri");
            }
            db.TBLMUSTERILER.Add(p1);
            db.SaveChanges();
            return View();
        }
        public ActionResult SIL(int id)
        {
            var musteri = db.TBLMUSTERILER.Find(id);
            db.TBLMUSTERILER.Remove(musteri);
            db.SaveChanges();
            return RedirectToAction("Index");

        }
        public ActionResult MusteriGetir(int id)
        {
            var mus = db.TBLMUSTERILER.Find(id);
            return View("MusteriGetir", mus);
        }

        public ActionResult Guncelle(TBLMUSTERILER p1)
        {
            var musteri = db.TBLMUSTERILER.Find(p1.MUSTERIID);
            musteri.MUSTERIAD = p1.MUSTERIAD;
            musteri.MUSTERISOYAD = p1.MUSTERISOYAD;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

MvcStok/Views/Musteri/Index.cshtml
@using MvcStok.Models.Entity
@model List<TBLMUSTERILER>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
@using (Html.BeginForm("Index", "Musteri", FormMethod.Post))
  {
    <p>
        Aranacak Müşteri Adı:@Html.TextBox("p")
        <input type="submit" value="Ara"/>
    </p>

   }
<table class="table table-bordered">
    <tr>
        <th>MÜŞTERİ ID</th>
        <td>MÜŞTERİ AD</td>
        <td>MÜŞTERİ SOYAD</td>
        <td>SİL</td>
        <td>GÜNCELLE</td>
        <td>ALERT</td>
       
    </tr>
    <tbody>
        @foreach (var mstr in Model)
        {
            <tr>
                <th>@mstr.MUSTERIID</th>
                <td>@mstr.MUSTERIAD</td>
                <td>@mstr.MUSTERISOYAD</td>
                <td><a href="/MUSTERI/SIL/@mstr.MUSTERIID" class="btn btn-danger">SİL</a></td>
                <td><a href="/MUSTERI/MusteriGetir/@mstr.MUSTERIID" class="btn btn-success">GÜNCELLE</a></td>
                <td>@Html.ActionLink("SİL BUTONU","SIL", new {id=mstr.MUSTERIID},new { @class="btn btn-warning", onclick="return confirm('Gerçekten silmek istiyor musunuz?')"})</td>
            </tr>

        }
    </tbody>

</table>
<a href="/MUSTERI/YeniMusteri/" class="btn btn-primary">YENİ MÜŞTERİ EKLE</a>

MvcStok/Views/Musteri/MusteriGetir.cshtml
@model MvcStok.Models.Entity.TBLMUSTERILER
@{
    ViewBag.Title = "MusteriGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
@using (Html.BeginForm("Guncelle", "Musteri", FormMethod.Post))
{
<div class="form-group">
    @Html.LabelFor(m => m.MUSTERIID)
    @Html.TextBoxFor(m => m.MUSTERIID, new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.MUSTERIAD)
    @Html.TextBoxFor(m => m.MUSTERIAD, new { @class = "form-control" })
    <br />
    @Html.LabelFor(m => m.MUSTERISOYAD)
    @Html.TextBoxFor(m => m.MUSTERISOYAD, new { @class = "form-control" })
</div>
<div>
    <button class="btn btn-warning">Müşteri Güncelle</button>
</div>

}

MvcStok/Views/Musteri/YeniMusteri.cshtml
@model MvcStok.Models.Entity.TBLMUSTERILER
@{
    ViewBag.Title = "YeniMusteri";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<form method="post" class="form-group">
    <div>
        <label>Müşteri Adı</label>
        @Html.TextBoxFor(m => m.MUSTERIAD, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.MUSTERIAD, "", new { @style = "color:green" })
    </div>
    <div>
        <label>Müşteri Soyadı</label>
        <input type="text" class="form-control" name="MUSTERISOYAD" />
    </div>
    <div style="margin-top:15px">
        <button class="btn btn-info" id="btn1">MÜŞTERİ EKLE</button> 
    </div>
    <script>
        $('#btn1').click(function () {
            alert('Müşteri Ekleme İşlemi Yapıldı.........!');
        });
    </script>
</form>