MvcStok/Controllers/KategoriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcStok.Models.Entity;
using PagedList;
using PagedList.Mvc;


namespace MvcStok.Controllers
{
    public class KategoriController : Controller
    {
        // GET: Kategori
        MvcDbStokEntities db = new MvcDbStokEntities();
        public ActionResult Index(int sayfa=1)
        {
            //var degerler = db.TBLKATEGORILER.ToList();
            var degerler = db.TBLKATEGORILER.ToList().ToPagedList(sayfa, 4);
            return View(degerler);
        } 
        [HttpGet]
        public ActionResult YeniKategori()
        {
            return View();
        }
        [HttpPost]
        public ActionResult YeniKategori(TBLKATEGORILER p1)
        {
            if (!ModelState.IsValid)
            {
                return View("YeniKategori");
            }
            db.TBLKATEGORILER.Add(p1);
            db.SaveChanges();
            return View();

        }
        public ActionResult SIL(int id)
        {
            var kategori = db.TBLKATEGORILER.Find(id);
            db.TBLKATEGORILER.Remove(kategori);
            db.SaveChanges();
            return RedirectToAction("Index");

        }
        public ActionResult KategoriGetir(int id)
        {
            var ktgr = db.TBLKATEGORILER.Find(id);
            return View("KategoriGetir", ktgr);
        }

        public ActionResult Guncelle(TBLKATEGORILER p1)
        {
            var ktg = db.TBLKATEGORILER.Find(p1.KATEGORIID);
            ktg.KATEGORIAD = p1.KATEGORIAD;
            db.SaveChanges();
            return RedirectToAction("Index");

            

        }
      

    }
}

MvcStok/Views/Kategori/Index.cshtml
@using MvcStok.Models.Entity
@using PagedList;
@using PagedList.Mvc;
@model PagedList.IPagedList<TBLKATEGORILER>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<table class="table table-bordered">
    <tr>
        <th>KATEGORİ ID</th>
        <th>KATEGORİ ADI</th>
        <th>SİL</th>
        <th>GÜNCELLE</th>
    </tr>
    <tbody>
        @foreach (var ktgr in Model)
        {
            <tr>

                <th>@ktgr.KATEGORIID</th>
                <td>@ktgr.KATEGORIAD</td>
                <td><a href="/KATEGORI/SIL/@ktgr.KATEGORIID" class="btn btn-danger">SİL</a></td>
                <td><a href="/KATEGORI/KategoriGetir/@ktgr.KATEGORIID" class="btn btn-success">GÜNCELLE</a></td>
            </tr>

        }

    </tbody>


</table>
@Html.PagedListPager((IPagedList)Model,sayfa=>Url.Action("Index",new { sayfa }))
<a href="/KATEGORI/YeniKategori/" class="btn btn-primary">YENİ KATEGORİ EKLE</a>

MvcStok/Views/Kategori/KategoriGetir.cshtml
@model MvcStok.Models.Entity.TBLKATEGORILER
@{
    ViewBag.Title = "KategoriGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
@using (Html.BeginForm("Guncelle", "Kategori", FormMethod.Post))
 {
    <div>
        @Html.LabelFor(m=>m.KATEGORIID)
        @Html.TextBoxFor(m=>m.KATEGORIID, new { @class="form-control"})
        <br />
        @Html.LabelFor(m=>m.KATEGORIAD)
        @Html.TextBoxFor(m=>m.KATEGORIAD, new { @class="form-control" })
    </div>
    <br />
    <div>
        <button class="btn btn-warning">Kategori Güncelle</button>
    </div>


    }

MvcStok/Views/Kategori/YeniKategori.cshtml
@model MvcStok.Models.Entity.TBLKATEGORILER
@{
    ViewBag.Title = "YeniKategori";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<form class="form-group" method="post">
   @* <div>
        <label>Kategori Adı</label>
        <input type="text" class="form-control" name="KATEGORIAD" />
    </div>*@
    <div>
        <label>Kategori Adı</label>
        @Html.TextBoxFor(m=>m.KATEGORIAD,new { @class="form-control"})
        @Html.ValidationMessageFor(m => m.KATEGORIAD, "", new {@style="color:blue"})
    </div>

    <div style="margin-top:15px">
        <button class="btn btn-info">Kategori Ekle</button>
    </div>

</form>